### ISSUE TITLE
Atlas generator can't contain duplicate image names

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#1]
If each folder will be an animation, then it'd be nice to automatically handle the naming of images within, to avoid conflicts (and having to rename files). Perhaps append the parent folders names (separated by underscores) to the dictionary key, since the folder path will be unique? (i.e Fighter_Down_001)

For example:

Characters/Fighter/Down/001.png ... 003.png
Characters/Fighter/Up/001.png ... 003.png

Throws:

> Build started 2016-02-14 9:27:27 PM

/Content/FighterMaleAtlas.xml
	----- adding animation: Down, frames: [0 - 2]
	----- adding animation: Left, frames: [3 - 5]
	----- adding animation: Right, frames: [6 - 8]
	----- adding animation: Up, frames: [9 - 11]
	Adding texture: 001
	Adding texture: 002
	Adding texture: 003
/Content/FighterMaleAtlas.xml: error: Processor 'TextureAtlasProcessor' had unexpected failure!
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Nez.TextureAtlasGenerator.TextureAtlasProcessor.Process(String[] input, ContentProcessorContext context) in \PipelineImporter\TextureAtlasGenerator\TextureAtlasProcessor.cs:line 75
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

**Comment by prime31** [comment]
I just pushed a change that uses "folder-filename" as the keys (so, Down-001, Up-001 would be the keys in your example). I'll probably make it configureable in the future so you can choose how many folders back to use in the key.
