### ISSUE TITLE
TypeLoadException on Game.Run()

### ISSUE THREAD

**Issue by DocY** [prime31/Nez#179]
```
An unhandled exception of type 'System.TypeLoadException' occurred in MonoGame.Framework.dll

Additional information: Could not load type 'Microsoft.Xna.Framework.Graphics.GraphicsMetrics' from assembly 'MonoGame.Framework, Version=3.4.0.456, Culture=neutral, PublicKeyToken=null'.
```

Using a standard Monogame Windows GL template with examples directly out of the getting started guide, it throws the exception just after the window opens and resizes. Same result referencing either the project or the pre-built dll.

Stepping into the Nez code puts me at the opening brace of Core.Update().

Program.cs:
```
using System;
namespace NezTest2
{
#if WINDOWS || LINUX

    public static class Program
    {
        [STAThread]
        static void Main()
        {
            using (var game = new Game1())
                game.Run();       // program bombs here
        }
    }
#endif
}
```

Game1.cs:
```
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Nez;
namespace NezTest2
{
    public class Game1 : Core
    {
        public Game1() : base(width: 1280, height: 768, isFullScreen: false, enableEntitySystems: false)
        { }
        protected override void Initialize()
        {
            base.Initialize();
            Window.AllowUserResizing = true;

            // create our Scene with the DefaultRenderer and a clear color of CornflowerBlue
            var myScene = Scene.createWithDefaultRenderer(Color.CornflowerBlue);

            // set the scene so Nez can take over
            scene = myScene;
        }
    }
}
```

Stack trace:
```
   at Nez.Core.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.OpenTKGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at NezTest2.Program.Main() in C:\(project path)\NezTest2\NezTest2\Program.cs:line 21
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by prime31** [comment]
Nez is compiled against MonoGame 3.5. It will not work with MonoGame 3.6 without modifications. You can use a Release build out of the box (which disables the debug draw call counting) or open the Core.cs file and comment out the code that accesses GraphicsMetrics.
