### ISSUE TITLE
NullReferenceException when initializing Core

### ISSUE THREAD

**Issue by Pyroglyph** [prime31/Nez#247]
### Problem
As soon as Core is initialized, a NullReferenceException happens on line 109 (Core's constructor definition).

Error details:

    System.NullReferenceException occurred
    HResult=0x80004003
    Message=Object reference not set to an instance of an object.
    Source=MonoGame.Framework
    StackTrace:
      at Microsoft.Xna.Framework.MetroGamePlatform..ctor(Game game)
      at Microsoft.Xna.Framework.GamePlatform.PlatformCreate(Game game)
      at Microsoft.Xna.Framework.Game..ctor()
      at Nez.Core..ctor(Int32 width, Int32 height, Boolean isFullScreen, Boolean enableEntitySystems, String windowTitle, String contentDirectory) in K:\Users\Connor\Documents\Visual Studio 2017\Projects\Nez\Nez.Portable\Core.cs:line 109
      at Test.Game1..ctor() in k:\users\connor\documents\visual studio 2017\Projects\Test\Test\Game1.cs:line 10
      at Test.Program.Main() in k:\users\connor\documents\visual studio 2017\Projects\Test\Test\Program.cs:line 17

### Reproduction:
1. Create a new MonoGame DesktopGL project.
2. Change the target framework of said project to 4.5.
3. Import the Nez project into the solution.
3. Reference the Nez project in your main project.
4. Make Game1 inherit from Nez.Core.
5. Change Exit() to exit() because MonoGame OpenGL doesn't like Exit() for some reason. It won't compile without changing this but it's probably not relevant to the issue.
6. Run

### Other comments
I've got a sinking feeling that I probably missed something really obvious but then again I've always had trouble with the OpenGL version of MonoGame. I've not seen anyone else with this problem either.

**Comment by Sakar** [comment]
I'm having the same issue, however it only occurs when I'm trying to launch with the debugger. Launching the exe directly from the output folder works fine. Curiously, if I check "Enabled native node debugging" in the project properties, this error doesn't occur.

**Comment by Pyroglyph** [comment]
Strange, those two don't work for me. When I run the .exe from the output folder the program doesn't show but appears in task manager for a little while then disappears and checking 'Enable native code debugging' just results in the same error being thrown.

**Comment by Kyle873** [comment]
Yeah, I'm getting the same issue here too. Setup according to the README but it's throwing an NRE on Window in the Core constructor because it's null.
