### ISSUE TITLE
MissingMethodException on Startup

### ISSUE THREAD

**Issue by nerdbaron** [prime31/Nez#306]
I just began using Nez, as I thought it might help my programming.  However, whenever the Core class runs, I get a MissingMethodException:

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'UInt64 Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount()'.
  Source=Nez
  StackTrace:
   at Nez.Core.Draw(GameTime gameTime) in C:\Users\Sean\Documents\Visual Studio 2017\Tools\prime31-Nez-1f76788\Nez.Portable\Core.cs:line 319
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at NezTest.Program.Main() in C:\Users\Sean\Documents\Visual Studio 2017\Projects\NezTest\NezTest\Program.cs:line 17

This doesn't occur when I run a Monogame program normally.  Any idea what I am doing wrong?

**Comment by prime31** [comment]
Please search the issues before posting. This has been brought up half a dozen times already.
